/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BookNew.java
 *
 * Created on Jan 5, 2013, 11:05:32 AM
 */
package gui;

import Classes.Book;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static Db.DB.*;

/**
 *
 * @author Group 20
 */
public class BookNew extends javax.swing.JPanel {

    /** Creates new form BookNew */
    Book book;

    public BookNew() {
        initComponents();
        book = new Book();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAddBook = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtAddBookId = new javax.swing.JTextField();
        txtAddIsbnNo = new javax.swing.JTextField();
        txtAddTitle = new javax.swing.JTextField();
        txtAddSerices = new javax.swing.JTextField();
        txtAddEdition = new javax.swing.JTextField();
        txtAddVolume = new javax.swing.JTextField();
        txtAddAuthor = new javax.swing.JTextField();
        txtAddAdditionlAuthor = new javax.swing.JTextField();
        txtAddPublisher = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAddSummary = new javax.swing.JTextArea();
        txtAddLanguage = new javax.swing.JTextField();
        dtAddAddDate = new datechooser.beans.DateChooserCombo();
        dtAddPubishDate = new datechooser.beans.DateChooserCombo();
        jLabel42 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnSearchMemberUpdate1 = new javax.swing.JButton();
        btnSearchMemberClear1 = new javax.swing.JButton();
        txtAddCategory = new javax.swing.JTextField();
        txtAddQuantity = new components.IntegerTextField();
        txtAddUnitPrice = new components.DoubleTextField();

        setBackground(new java.awt.Color(102, 102, 102));

        pnlAddBook.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("Book Id :");

        jLabel2.setText("ISBN No :");

        jLabel3.setText("Title :");

        jLabel4.setText("Series :");

        jLabel5.setText("Category :");

        jLabel6.setText("Edition :");

        jLabel7.setText("Volume :");

        jLabel8.setText("Language :");

        jLabel9.setText("Author :");

        jLabel10.setText("Additional Author :");

        jLabel12.setText("Add Date :");

        jLabel13.setText("Publisher :");

        jLabel14.setText("Published Date :");

        jLabel18.setText("Summary :");

        txtAddBookId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAddBookIdFocusLost(evt);
            }
        });

        txtAddSummary.setColumns(20);
        txtAddSummary.setRows(5);
        jScrollPane4.setViewportView(txtAddSummary);

        jLabel42.setText("Qunttity :");

        jLabel38.setText("Price :");

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnSearchMemberUpdate1.setText("Save");
        btnSearchMemberUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchMemberUpdate1ActionPerformed(evt);
            }
        });

        btnSearchMemberClear1.setText("Clear");
        btnSearchMemberClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchMemberClear1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSearchMemberUpdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnSearchMemberClear1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchMemberUpdate1)
                    .addComponent(btnSearchMemberClear1))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlAddBookLayout = new javax.swing.GroupLayout(pnlAddBook);
        pnlAddBook.setLayout(pnlAddBookLayout);
        pnlAddBookLayout.setHorizontalGroup(
            pnlAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddBookLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel42)
                    .addComponent(jLabel38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAddUnitPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAddQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAddCategory)
                    .addComponent(dtAddPubishDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAddPublisher, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dtAddAddDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAddLanguage)
                    .addComponent(txtAddAuthor)
                    .addComponent(txtAddAdditionlAuthor)
                    .addComponent(txtAddTitle)
                    .addComponent(txtAddSerices)
                    .addComponent(txtAddIsbnNo)
                    .addComponent(txtAddVolume)
                    .addComponent(txtAddEdition, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addComponent(txtAddBookId))
                .addGap(85, 85, 85)
                .addGroup(pnlAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(pnlAddBookLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pnlAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))))
                .addGap(119, 119, 119))
        );
        pnlAddBookLayout.setVerticalGroup(
            pnlAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddBookLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddBookId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddBookLayout.createSequentialGroup()
                        .addGroup(pnlAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAddIsbnNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAddTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAddSerices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtAddCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAddEdition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAddVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtAddLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAddAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                .addGroup(pnlAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddBookLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAddAdditionlAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dtAddAddDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAddPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dtAddPubishDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel42)
                            .addComponent(txtAddQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAddBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(txtAddUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlAddBookLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(pnlAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(pnlAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchMemberUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchMemberUpdate1ActionPerformed
        book.bookId = txtAddBookId.getText();
        book.isbn = txtAddIsbnNo.getText();
        book.title = txtAddTitle.getText();
        book.series = txtAddSerices.getText();
        book.category = txtAddCategory.getText();
        book.edition = txtAddEdition.getText();
        book.volume = txtAddVolume.getText();
        book.language = txtAddLanguage.getText();
        book.author1 = txtAddAuthor.getText();
        book.author2 = txtAddAdditionlAuthor.getText();
        book.addDate = dtAddAddDate.getSelectedDate().getTime();
        book.publisher = txtAddPublisher.getText();
        book.publishDate = dtAddPubishDate.getSelectedDate().getTime();
        try {
            book.quantity = Integer.parseInt(txtAddQuantity.getText());
            book.price = Double.parseDouble(txtAddUnitPrice.getText());
            book.summary = txtAddSummary.getText();
            if (book.bookId.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Book ID cannot be empty...");
            } else {
                saveData(book);
                JOptionPane.showMessageDialog(null, "Save success");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "You have entered invalid values for Quantity Or Unit price.");
            Logger.getLogger(BookNew.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Save failed");
            Logger.getLogger(BookNew.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            book.reset();
        }


    }//GEN-LAST:event_btnSearchMemberUpdate1ActionPerformed

    private void txtAddBookIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAddBookIdFocusLost
        if (!txtAddBookId.getText().isEmpty()) {
            ResultSet rset = null;
            Statement stmt=null;
            try {
                stmt=getConnection().createStatement();
                rset = stmt.executeQuery("SELECT * FROM book WHERE book_id='" + txtAddBookId.getText() + "'");
                if (rset.next()) {
                    JOptionPane.showMessageDialog(null, "This book ID is already entered. Use different ID");
                    txtAddBookId.setText("");
                }
            } catch (Exception ex) {
                Logger.getLogger(BookNew.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    rset.close();
                    stmt.close();
                } catch (SQLException ex) {
                    Logger.getLogger(BookNew.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_txtAddBookIdFocusLost

    private void btnSearchMemberClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchMemberClear1ActionPerformed
        txtAddAdditionlAuthor.setText("");
        txtAddAuthor.setText("");
        txtAddBookId.setText("");
        txtAddCategory.setText("");
        txtAddEdition.setText("");
        txtAddIsbnNo.setText("");
        txtAddLanguage.setText("");
        txtAddPublisher.setText("");
        txtAddQuantity.setText("");
        txtAddSerices.setText("");
        txtAddSummary.setText("");
        txtAddTitle.setText("");
        txtAddUnitPrice.setText("");
        txtAddVolume.setText("");
        book.reset();
    }//GEN-LAST:event_btnSearchMemberClear1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearchMemberClear1;
    private javax.swing.JButton btnSearchMemberUpdate1;
    private datechooser.beans.DateChooserCombo dtAddAddDate;
    private datechooser.beans.DateChooserCombo dtAddPubishDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel pnlAddBook;
    private javax.swing.JTextField txtAddAdditionlAuthor;
    private javax.swing.JTextField txtAddAuthor;
    private javax.swing.JTextField txtAddBookId;
    private javax.swing.JTextField txtAddCategory;
    private javax.swing.JTextField txtAddEdition;
    private javax.swing.JTextField txtAddIsbnNo;
    private javax.swing.JTextField txtAddLanguage;
    private javax.swing.JTextField txtAddPublisher;
    private components.IntegerTextField txtAddQuantity;
    private javax.swing.JTextField txtAddSerices;
    private javax.swing.JTextArea txtAddSummary;
    private javax.swing.JTextField txtAddTitle;
    private components.DoubleTextField txtAddUnitPrice;
    private javax.swing.JTextField txtAddVolume;
    // End of variables declaration//GEN-END:variables
}
