/*
 * LogIn.java
 *
 * Created on January 6, 2010, 6:48 PM
 */
package gui;

import Classes.GuiManager;
import com.sun.awt.AWTUtilities;
import java.awt.Color;
import static Db.DB.*;
import java.io.File;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author  Group 20
 */
public class LogIn extends javax.swing.JFrame {

    /** Creates new form LogIn */
    public LogIn() {
        initComponents();
        try {
            cmbxLgInUsrType.setModel(Db.DB.getMemberType());
        } catch (Exception ex) {
            Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
        }
        getRootPane().setDefaultButton(btnLogIn);
        
        setUndecorated(true);
        try {
            pnlLogin.setBackground(new Color(0, 0, 0, 50));
            //AWTUtilities.setWindowOpaque(this, false);
        } catch (Exception ex) {
            setBackground(new Color(0, 0, 0, 0));
            JOptionPane.showMessageDialog(null, "Your JVM is not the latest...");
        }
    }

    private void showMainFrame(String userType, String userName) {
        lblGreenImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/key_lock-animated.gif")));

        final String ut = userType;
        final String un = userName;
        final LogIn l = this;

        new Thread(new Runnable() {

            @Override
            public void run() {
                try {
                    Thread.sleep(2000);
                    java.awt.EventQueue.invokeLater(new Runnable() {

                        @Override
                        public void run() {
                            new MainFrame(ut, un).setVisible(true);
                            l.dispose();
                        }
                    });
                } catch (InterruptedException ex) {
                    Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }).start();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblGreenImage = new javax.swing.JLabel();
        pnlLogin = new javax.swing.JPanel();
        cmbxLgInUsrType = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLogInUserName = new javax.swing.JTextField();
        pswdLogIn = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        btnLogIn = new javax.swing.JButton();
        btnLogInExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log In");
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(56, 69, 35));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel2.setDisplayedMnemonic('W');
        jLabel2.setFont(new java.awt.Font("Cambria", 0, 18));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Login to our Library System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(371, 371, 371))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 596, -1));

        lblGreenImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/key_lock-animated2.png"))); // NOI18N
        getContentPane().add(lblGreenImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 300, 232));

        pnlLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cmbxLgInUsrType.setFont(new java.awt.Font("Cambria", 0, 14));
        cmbxLgInUsrType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "[ Select ]" }));
        cmbxLgInUsrType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxLgInUsrTypeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 14));
        jLabel4.setText("   User Type :");
        jLabel4.setOpaque(true);

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 14));
        jLabel3.setText("  User Name :");
        jLabel3.setOpaque(true);

        txtLogInUserName.setFont(new java.awt.Font("Cambria", 0, 14));

        pswdLogIn.setFont(new java.awt.Font("Cambria", 0, 14));

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel5.setText("  Password :");
        jLabel5.setOpaque(true);

        btnLogIn.setFont(new java.awt.Font("Cambria", 0, 14));
        btnLogIn.setText("Log In");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });

        btnLogInExit.setFont(new java.awt.Font("Cambria", 0, 14));
        btnLogInExit.setText("Exit");
        btnLogInExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(cmbxLgInUsrType, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLogInUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pswdLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnLogIn)
                        .addGap(18, 18, 18)
                        .addComponent(btnLogInExit, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbxLgInUsrType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogInUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pswdLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(24, 24, 24)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogIn)
                    .addComponent(btnLogInExit))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(pnlLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 280, 170));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-612)/2, (screenSize.height-333)/2, 612, 333);
    }// </editor-fold>//GEN-END:initComponents

private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed

//    File f = new File("daatt.mm");
//    String s = 
    
    try {
        Statement stmt = getConnection().createStatement();
        ResultSet rset = stmt.executeQuery("SELECT gui_id FROM permission "
                + "WHERE member_type='" + cmbxLgInUsrType.getSelectedItem().toString() + "' "
                + "AND gui_id='" + GuiManager.LOGIN_WITHOUT_USERNAME + "'");
        if (rset.next()) {
            txtLogInUserName.setEnabled(false);
            pswdLogIn.setEnabled(false);
            showMainFrame(cmbxLgInUsrType.getSelectedItem().toString(), txtLogInUserName.getText());
        } else {
            rset.close();
            stmt.close();

            stmt = getConnection().createStatement();
            //String qry = "SELECT * FROM member WHERE member_type='" + cmbxLgInUsrType.getSelectedItem().toString() + "' AND "
               //     + "member_id='" + txtLogInUserName.getText() + "' AND psw='" + String.valueOf(pswdLogIn.getPassword()) + "'";
            
            String qry = "SELECT * FROM member WHERE member_type='" + cmbxLgInUsrType.getSelectedItem().toString() + "' AND "
                   + "member_id='" + txtLogInUserName.getText() + "' AND psw=PASSWORD('" + String.valueOf(pswdLogIn.getPassword()) + "')";
           rset = stmt.executeQuery(qry);
            if (rset.next()) {
                showMainFrame(cmbxLgInUsrType.getSelectedItem().toString(), txtLogInUserName.getText());
            } else {

                new Thread(new Runnable() {

                    @Override
                    public void run() {
                        try {
                            lblGreenImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/key_lock-animated.gif")));
                            Thread.sleep(4000);
                            lblGreenImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/key_lock-animated2.png")));
                        } catch (InterruptedException ex) {
                            Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        JOptionPane.showMessageDialog(null, "Invalid user name or password entered.");
                    }
                }).start();
            }
            rset.close();
            stmt.close();
        }

    } catch (Exception ex) {
        Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
    }
}//GEN-LAST:event_btnLogInActionPerformed

private void btnLogInExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInExitActionPerformed
    System.exit(0);
}//GEN-LAST:event_btnLogInExitActionPerformed

private void cmbxLgInUsrTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxLgInUsrTypeActionPerformed
    try {
        Statement stmt = getConnection().createStatement();
        ResultSet rset = stmt.executeQuery("SELECT gui_id FROM permission "
                + "WHERE member_type='" + cmbxLgInUsrType.getSelectedItem().toString() + "' "
                + "AND gui_id='" + GuiManager.LOGIN_WITHOUT_USERNAME + "'");
        if (rset.next()) {
            txtLogInUserName.setEnabled(false);
            pswdLogIn.setEnabled(false);
        } else {
            txtLogInUserName.setEnabled(true);
            pswdLogIn.setEnabled(true);
        }
        rset.close();
        stmt.close();
        txtLogInUserName.grabFocus();
    } catch (Exception ex) {
        Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
    }
}//GEN-LAST:event_cmbxLgInUsrTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton btnLogInExit;
    private javax.swing.JComboBox cmbxLgInUsrType;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblGreenImage;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPasswordField pswdLogIn;
    private javax.swing.JTextField txtLogInUserName;
    // End of variables declaration//GEN-END:variables
}
