/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ManageBooksReturn.java
 *
 * Created on Jan 5, 2013, 11:06:11 AM
 */
package gui;

import Classes.Lend_Return;
import Db.DB;
import javax.swing.JFrame;
import javax.swing.WindowConstants;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import java.util.HashMap;
import java.util.Map;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
//import net.sf.jasperreports.engine.JREmptyDataSource;
import static Db.DB.*;

/**
 *
 * @author Group 20
 */
public class ManageBooksReturn extends javax.swing.JPanel {

    /** Creates new form ManageBooksReturn */
    boolean bookOk;
    boolean memberOk;
    DefaultTableModel tbl;

    public ManageBooksReturn() {
        initComponents();
        tbl = (DefaultTableModel) tblReturnBook.getModel();
    }

    private void loadTable() {
        java.util.Date today = new java.util.Date();
        try {
            Statement stmt = getConnection().createStatement();
            ResultSet rset = stmt.executeQuery("SELECT fine FROM lend_days_fine "
                    + "WHERE member_type='" + cmbReturnMemberType.getSelectedItem().toString() + "'");
            double fine = 0;
            if (rset.next()) {
                fine = rset.getDouble(1);
            }

            rset = stmt.executeQuery("SELECT b.book_id, title, lend_date, should_return_date FROM lend_return l, book b "
                    + "WHERE member_type='" + cmbReturnMemberType.getSelectedItem().toString() + "' AND "
                    + "member_id='" + txtReturnMemberId.getText() + "' AND return_date < lend_date AND l.book_id=b.book_id");

            tbl.setRowCount(0);
            while (rset.next()) {
                ArrayList ast = new ArrayList();

                ast.add(rset.getString(1));
                ast.add(rset.getString(2));
                ast.add(rset.getDate(3));
                ast.add(rset.getDate(4));

                Date shldRetrnOn = rset.getDate(4);
                if (isBookLate(shldRetrnOn, today)) {
                    ast.add(fine * getLateDays(shldRetrnOn, today));
                } else {
                    ast.add(0);
                }
                tbl.addRow(ast.toArray());
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageBooksLend.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private long getLateDays(Date shouldReturnOn, java.util.Date returnDay) {
        return ((returnDay.getTime() - shouldReturnOn.getTime()) / 86400000);
    }

    private boolean isBookLate(Date shouldReturnOn, java.util.Date returnDay) {
        long l1 = returnDay.getTime();
        long l2 = shouldReturnOn.getTime();
        long l3 = l1 - l2;
        if (l3 > 0) {
            return true;
        } else {
            return false;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlReturnBook = new javax.swing.JPanel();
        lblMainMemberID1 = new javax.swing.JLabel();
        lblMainBookId1 = new javax.swing.JLabel();
        txtReturnMemberId = new javax.swing.JTextField();
        txtReturnBookId = new javax.swing.JTextField();
        btnReturnSave = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblReturnBook = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnReturnPrintFine = new javax.swing.JButton();
        lblMainBookId2 = new javax.swing.JLabel();
        txtReturnFine = new components.DoubleTextField();
        lblMainMemberID2 = new javax.swing.JLabel();
        cmbReturnMemberType = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(153, 153, 153));

        pnlReturnBook.setBackground(new java.awt.Color(204, 204, 204));

        lblMainMemberID1.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblMainMemberID1.setText("Member ID :");

        lblMainBookId1.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblMainBookId1.setText("Book ID :");

        txtReturnMemberId.setFont(new java.awt.Font("Tahoma", 0, 12));
        txtReturnMemberId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtReturnMemberIdFocusLost(evt);
            }
        });

        txtReturnBookId.setEditable(false);
        txtReturnBookId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtReturnBookId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtReturnBookIdFocusLost(evt);
            }
        });

        btnReturnSave.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnReturnSave.setText("Return");
        btnReturnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnSaveActionPerformed(evt);
            }
        });

        tblReturnBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Book Name", "Lend Date", "Shold Return On", "Fine"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblReturnBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblReturnBookMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(tblReturnBook);

        jPanel1.setEnabled(false);

        btnReturnPrintFine.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnReturnPrintFine.setText("Print");
        btnReturnPrintFine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnPrintFineActionPerformed(evt);
            }
        });

        lblMainBookId2.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblMainBookId2.setText("Fine Amount : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnReturnPrintFine, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMainBookId2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtReturnFine, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMainBookId2)
                    .addComponent(txtReturnFine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnReturnPrintFine)
                .addGap(4, 4, 4))
        );

        lblMainMemberID2.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblMainMemberID2.setText("Member Type :");

        cmbReturnMemberType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "[select type]" }));
        cmbReturnMemberType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbReturnMemberTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlReturnBookLayout = new javax.swing.GroupLayout(pnlReturnBook);
        pnlReturnBook.setLayout(pnlReturnBookLayout);
        pnlReturnBookLayout.setHorizontalGroup(
            pnlReturnBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReturnBookLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlReturnBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlReturnBookLayout.createSequentialGroup()
                        .addGroup(pnlReturnBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnReturnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlReturnBookLayout.createSequentialGroup()
                                .addGroup(pnlReturnBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblMainBookId1)
                                    .addComponent(lblMainMemberID1)
                                    .addComponent(lblMainMemberID2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlReturnBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbReturnMemberType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtReturnBookId, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtReturnMemberId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pnlReturnBookLayout.setVerticalGroup(
            pnlReturnBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReturnBookLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlReturnBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlReturnBookLayout.createSequentialGroup()
                        .addGroup(pnlReturnBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMainMemberID2)
                            .addComponent(cmbReturnMemberType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlReturnBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtReturnMemberId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMainMemberID1))
                        .addGap(8, 8, 8)
                        .addGroup(pnlReturnBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtReturnBookId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMainBookId1)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReturnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addComponent(pnlReturnBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(pnlReturnBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtReturnMemberIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtReturnMemberIdFocusLost
        if (!txtReturnMemberId.getText().isEmpty()) {
            try {
                Statement stmt = getConnection().createStatement();
                ResultSet rset = stmt.executeQuery("SELECT member_id FROM member "
                        + "WHERE member_type='" + cmbReturnMemberType.getSelectedItem().toString() + "' AND "
                        + "member_id='" + txtReturnMemberId.getText() + "'");
                if (rset.next()) {
                    memberOk = true;
                    loadTable();

                } else {
                    memberOk = false;
                    JOptionPane.showMessageDialog(null, "Entered user id not found from the selected user type.\n"
                            + "This user might not have register yet.");
                }
                rset.close();
                stmt.close();
            } catch (Exception ex) {
                Logger.getLogger(ManageBooksLend.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
}//GEN-LAST:event_txtReturnMemberIdFocusLost

    private void txtReturnBookIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtReturnBookIdFocusLost
        if (!txtReturnBookId.getText().isEmpty()) {
            try {
                Statement stmt = getConnection().createStatement();
                ResultSet rset = stmt.executeQuery("SELECT book_id FROM book WHERE "
                        + "book_id='" + txtReturnBookId.getText() + "'");
                if (rset.next()) {
                    bookOk = true;
                } else {
                    bookOk = false;
                    JOptionPane.showMessageDialog(null, "Entered book id not found.\n"
                            + "This book might not have register yet.");
                }
                rset.close();
                stmt.close();
            } catch (Exception ex) {
                Logger.getLogger(ManageBooksLend.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
}//GEN-LAST:event_txtReturnBookIdFocusLost

    private void btnReturnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnSaveActionPerformed
        try {
            Calendar c=Calendar.getInstance();
            String[] temp;
            temp=tblReturnBook.getValueAt(tblReturnBook.getSelectedRow(), 2).toString().split("-");
            c.set(Integer.parseInt(temp[0]), Integer.parseInt(temp[1]), Integer.parseInt(temp[2]));
            Date lend=new Date(c.getTimeInMillis());
            
            temp=tblReturnBook.getValueAt(tblReturnBook.getSelectedRow(), 3).toString().split("-");
            c.set(Integer.parseInt(temp[0]), Integer.parseInt(temp[1]), Integer.parseInt(temp[2]));
            Date sReturn=new Date(c.getTimeInMillis());
            
            Date today=new Date(new java.util.Date().getTime());
            
            DB.updateData(new Lend_Return(cmbReturnMemberType.getSelectedItem().toString(), txtReturnMemberId.getText(), txtReturnBookId.getText(), lend, sReturn, today));
            JOptionPane.showMessageDialog(null, "Saved OK.");
            loadTable();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Saved failed.");
            Logger.getLogger(ManageBooksReturn.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_btnReturnSaveActionPerformed

    private void btnReturnPrintFineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnPrintFineActionPerformed
        try {
            String reportSource = System.getProperty("user.dir") + "/print/Receipt.jrxml";
            Map<String, Object> params = new HashMap<String, Object>();
            params.put("m_type", cmbReturnMemberType.getSelectedItem().toString());
            params.put("m_id", txtReturnMemberId.getText());
            params.put("b_id", txtReturnBookId.getText());
            params.put("amount", txtReturnFine.getText());
            params.put("fine_date", new Date(new java.util.Date().getTime()).toString());

            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, params, new JREmptyDataSource());
            JasperViewer.viewReport(jasperPrint, false);
        } catch (JRException ex) {
            Logger.getLogger(ManageBooksReturn.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_btnReturnPrintFineActionPerformed

    private void tblReturnBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblReturnBookMouseClicked
        if (tblReturnBook.getSelectedRowCount() > 0) {
            txtReturnBookId.setText(tblReturnBook.getValueAt(tblReturnBook.getSelectedRow(), 0).toString());
            txtReturnFine.setText(tblReturnBook.getValueAt(tblReturnBook.getSelectedRow(), 4).toString());
            if (txtReturnFine.getText().equals("0")) {
                txtReturnFine.setEditable(false);
                btnReturnPrintFine.setEnabled(false);
            } else {
                txtReturnFine.setEditable(true);
                btnReturnPrintFine.setEnabled(true);
            }
            txtReturnBookIdFocusLost(null);
        }
    }//GEN-LAST:event_tblReturnBookMouseClicked

    private void cmbReturnMemberTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbReturnMemberTypeActionPerformed
        txtReturnMemberId.grabFocus();
    }//GEN-LAST:event_cmbReturnMemberTypeActionPerformed
    public static void main(String[] args) {
        JFrame jf = new JFrame("First Run");
        ManageBooksReturn mbr=new ManageBooksReturn();
        jf.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        jf.add(mbr);
        jf.setResizable(false);
        jf.pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        jf.setBounds((screenSize.width - 541) / 2, (screenSize.height - 488) / 2, mbr.getWidth(), mbr.getHeight());
        
        jf.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReturnPrintFine;
    private javax.swing.JButton btnReturnSave;
    public javax.swing.JComboBox cmbReturnMemberType;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lblMainBookId1;
    private javax.swing.JLabel lblMainBookId2;
    private javax.swing.JLabel lblMainMemberID1;
    private javax.swing.JLabel lblMainMemberID2;
    private javax.swing.JPanel pnlReturnBook;
    private javax.swing.JTable tblReturnBook;
    private javax.swing.JTextField txtReturnBookId;
    private components.DoubleTextField txtReturnFine;
    private javax.swing.JTextField txtReturnMemberId;
    // End of variables declaration//GEN-END:variables
}
