/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ManageBooksLend.java
 *
 * Created on Jan 5, 2013, 11:06:00 AM
 */
package gui;

import Classes.Lend_Return;
import java.sql.Date;
import static Db.DB.*;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Group 20
 */
public class ManageBooksLend extends javax.swing.JPanel {

    /** Creates new form ManageBooksLend */
    boolean bookOk;
    boolean memberOk;
    DefaultTableModel tbl;

    public ManageBooksLend() {
        initComponents();
        tbl = (DefaultTableModel) tblLendBook.getModel();
    }

    private void loadTable() {
        try {
            Statement stmt = getConnection().createStatement();
            ResultSet rset = stmt.executeQuery("SELECT b.book_id, b.title, should_return_date FROM lend_return l, book b "
                    + "WHERE member_type='" + cmbLendMemberType.getSelectedItem().toString() + "' AND "
                    + "member_id='" + txtLendMemberId.getText() + "' AND l.book_id=b.book_id");
            tbl.setRowCount(0);
            while (rset.next()) {
                ArrayList ast = new ArrayList();
                ast.add(rset.getString(1));
                ast.add(rset.getString(2));
                ast.add(rset.getDate(3));
                tbl.addRow(ast.toArray());
            }
            rset.close();
            stmt.close();
        } catch (Exception ex) {
            Logger.getLogger(ManageBooksLend.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLendBook = new javax.swing.JPanel();
        lblMainMemberID = new javax.swing.JLabel();
        lblMainBookId = new javax.swing.JLabel();
        txtLendMemberId = new javax.swing.JTextField();
        txtLendBookId = new javax.swing.JTextField();
        btnLendSave = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblLendBook = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        cmbLendMemberType = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        dtLendReturn = new datechooser.beans.DateChooserCombo();

        setBackground(new java.awt.Color(153, 153, 153));

        pnlLendBook.setBackground(new java.awt.Color(204, 204, 204));

        lblMainMemberID.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblMainMemberID.setText("Member ID :");

        lblMainBookId.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblMainBookId.setText("Book ID :");

        txtLendMemberId.setFont(new java.awt.Font("Tahoma", 0, 12));
        txtLendMemberId.setNextFocusableComponent(txtLendBookId);
        txtLendMemberId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLendMemberIdFocusLost(evt);
            }
        });

        txtLendBookId.setFont(new java.awt.Font("Tahoma", 0, 12));
        txtLendBookId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLendBookIdFocusLost(evt);
            }
        });

        btnLendSave.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnLendSave.setText("Enter");
        btnLendSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLendSaveActionPerformed(evt);
            }
        });

        tblLendBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Book Name", "Should Return On"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tblLendBook);

        jLabel11.setText("Member Type :");

        cmbLendMemberType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "[select type]" }));

        jLabel15.setText("Book Return Date :");

        javax.swing.GroupLayout pnlLendBookLayout = new javax.swing.GroupLayout(pnlLendBook);
        pnlLendBook.setLayout(pnlLendBookLayout);
        pnlLendBookLayout.setHorizontalGroup(
            pnlLendBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLendBookLayout.createSequentialGroup()
                .addGroup(pnlLendBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLendBookLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(pnlLendBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLendSave, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlLendBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pnlLendBookLayout.createSequentialGroup()
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(dtLendReturn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblMainBookId)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtLendBookId, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlLendBookLayout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cmbLendMemberType, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(45, 45, 45)
                                    .addComponent(lblMainMemberID)
                                    .addGap(5, 5, 5)
                                    .addComponent(txtLendMemberId, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pnlLendBookLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        pnlLendBookLayout.setVerticalGroup(
            pnlLendBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLendBookLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlLendBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLendBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMainMemberID)
                        .addComponent(cmbLendMemberType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addComponent(txtLendMemberId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlLendBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLendBookLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(pnlLendBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLendBookId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMainBookId)))
                    .addGroup(pnlLendBookLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlLendBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dtLendReturn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))))
                .addGap(11, 11, 11)
                .addComponent(btnLendSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(pnlLendBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(pnlLendBook, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtLendMemberIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLendMemberIdFocusLost
        if (!txtLendMemberId.getText().isEmpty()) {
            tbl.setRowCount(0);
            try {
                Statement stmt = getConnection().createStatement();
                ResultSet rset = stmt.executeQuery("SELECT member_id FROM member "
                        + "WHERE member_type='" + cmbLendMemberType.getSelectedItem().toString() + "' AND "
                        + "member_id='" + txtLendMemberId.getText() + "'");
                if (rset.next()) {
                    memberOk = true;
                    loadTable();

                } else {
                    memberOk = false;
                    JOptionPane.showMessageDialog(null, "Entered user id not found from the selected user type.\n"
                            + "This user might not have register yet.");
                }
                rset.close();
                stmt.close();
            } catch (Exception ex) {
                Logger.getLogger(ManageBooksLend.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
}//GEN-LAST:event_txtLendMemberIdFocusLost

    private void txtLendBookIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLendBookIdFocusLost
        if (!txtLendBookId.getText().isEmpty()) {
            try {
                Statement stmt = getConnection().createStatement();
                ResultSet rset = stmt.executeQuery("SELECT book_id FROM book WHERE "
                        + "book_id='" + txtLendBookId.getText() + "'");
                if (rset.next()) {
                    bookOk = true;
                } else {
                    bookOk = false;
                    JOptionPane.showMessageDialog(null, "Entered book id not found.\n"
                            + "This book might not have register yet.");
                }
                rset.close();
                stmt.close();
            } catch (Exception ex) {
                Logger.getLogger(ManageBooksLend.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
}//GEN-LAST:event_txtLendBookIdFocusLost

    private void btnLendSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLendSaveActionPerformed
        if (bookOk && memberOk) {
            try {

                String userType = cmbLendMemberType.getSelectedItem().toString();
                Date lendDate = new Date(new java.util.Date().getTime());
                Date shouldReturnOn = new Date(dtLendReturn.getSelectedDate().getTimeInMillis());

                Statement stmt = getConnection().createStatement();
                ResultSet rset = stmt.executeQuery("SELECT lend_days, max_book FROM lend_days_fine "
                        + "WHERE member_type='" + userType + "'");

                int maxBook = 0;
                int currentBook = 0;

                if (rset.next()) {
                    Calendar c = Calendar.getInstance();
                    c.set(c.get(1), c.get(2), c.get(5) + rset.getInt(1));
                    maxBook = rset.getInt(2);
                    dtLendReturn.setSelectedDate(c);
                }
                rset = stmt.executeQuery("SELECT COUNT(*) FROM lend_return WHERE member_type='" + userType + "' AND "
                        + "member_id='" + txtLendMemberId.getText() + "' AND return_date<lend_date");
                if (rset.next()) {
                    currentBook = rset.getInt(1);
                }
                rset.close();
                stmt.close();

                if (currentBook <= maxBook) {
                    Calendar c = Calendar.getInstance();
                    c.set(c.get(1), c.get(2), c.get(5) - 100000);
                    Date returnDate = new Date(c.getTimeInMillis());

                    Lend_Return lr = new Lend_Return(userType, txtLendMemberId.getText(), txtLendBookId.getText(), lendDate, shouldReturnOn, returnDate);

                    saveData(lr);
                    loadTable();
                    JOptionPane.showMessageDialog(null, "Done");
                }else{
                    JOptionPane.showMessageDialog(null, "This member has reach max book count.");
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error occured while saving data");
                Logger.getLogger(ManageBooksLend.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Unknown member or book!");
        }
    }//GEN-LAST:event_btnLendSaveActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLendSave;
    public javax.swing.JComboBox cmbLendMemberType;
    private datechooser.beans.DateChooserCombo dtLendReturn;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblMainBookId;
    private javax.swing.JLabel lblMainMemberID;
    private javax.swing.JPanel pnlLendBook;
    private javax.swing.JTable tblLendBook;
    private javax.swing.JTextField txtLendBookId;
    private javax.swing.JTextField txtLendMemberId;
    // End of variables declaration//GEN-END:variables
}
